INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (1, 'AX', 'Aaland Islands', '', 'ALA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (2, 'AF', 'Afghanistan', '', 'AFG', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (3, 'AL', 'Albania', 'Shqipëria', 'ALB', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (4, 'DZ', 'Algeria', 'ﺮﺌﺎﺰﺠﻠﺍ', 'DZA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (5, 'AS', 'American Samoa', '', 'ASM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (6, 'AD', 'Andorra', '', 'AND', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (7, 'AO', 'Angola', '', 'AGO', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (8, 'AI', 'Anguilla', '', 'AIA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (9, 'AQ', 'Antarctica', '', 'ATA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (10, 'AG', 'Antigua and Barbuda', '', 'ATG', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (11, 'AR', 'Argentina', 'Argentina', 'ARG', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (12, 'AM', 'Armenia', '', 'ARM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (13, 'AW', 'Aruba', '', 'ABW', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (14, 'AC', 'Ascension Island (British)', '', 'ASC', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (15, 'AU', 'Australia', 'Australia', 'AUS', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (16, 'AT', 'Austria', 'Österreich', 'AUT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (17, 'AZ', 'Azerbaijan', '', 'AZE', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (18, 'BS', 'Bahamas', '', 'BHS', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (19, 'BH', 'Bahrain', 'ﻦﻴﺮﺤﺐﻠﺍ', 'BHR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (20, 'BD', 'Bangladesh', '', 'BGD', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (21, 'BB', 'Barbados', '', 'BRB', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (22, 'BY', 'Belarus', 'Беларусь', 'BLR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (23, 'BE', 'Belgium', 'België', 'BEL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (24, 'BZ', 'Belize', '', 'BLZ', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (25, 'BJ', 'Benin', '', 'BEN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (26, 'BM', 'Bermuda', '', 'BMU', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (27, 'BT', 'Bhutan', '', 'BTN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (28, 'BO', 'Bolivia', 'Bolivia', 'BOL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (29, 'BQ', 'Bonaire, Sint Eustatius and Saba', '', 'BES', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (30, 'BA', 'Bosnia and Herzegovina', '', 'BIH', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (31, 'BW', 'Botswana', '', 'BWA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (32, 'BV', 'Bouvet Island', '', 'BVT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (33, 'BR', 'Brazil', 'Brasil', 'BRA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (34, 'IO', 'British Indian Ocean Territory', '', 'IOT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (35, 'BN', 'Brunei Darussalam', '', 'BRN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (36, 'BG', 'Bulgaria', 'България', 'BGR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (37, 'BF', 'Burkina Faso', '', 'BFA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (38, 'BI', 'Burundi', '', 'BDI', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (39, 'KH', 'Cambodia', '', 'KHM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (40, 'CM', 'Cameroon', '', 'CMR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (41, 'CA', 'Canada', 'Canada', 'CAN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (42, 'IC', 'Canary Islands', '', 'ICA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (43, 'CV', 'Cape Verde', '', 'CPV', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (44, 'KY', 'Cayman Islands', '', 'CYM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (45, 'CF', 'Central African Republic', '', 'CAF', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (46, 'TD', 'Chad', '', 'TCD', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (47, 'CL', 'Chile', 'Chile', 'CHL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (48, 'CN', 'China', '中国(中华人民共和国)', 'CHN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (49, 'CX', 'Christmas Island', '', 'CXR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (50, 'CC', 'Cocos (Keeling) Islands', '', 'CCK', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (51, 'CO', 'Colombia', 'Colombia', 'COL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (52, 'KM', 'Comoros', '', 'COM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (53, 'CG', 'Congo', '', 'COG', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (54, 'CK', 'Cook Islands', '', 'COK', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (55, 'CR', 'Costa Rica', 'Costa Rica', 'CRI', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (56, 'CI', 'Cote D\'Ivoire', '', 'CIV', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (57, 'HR', 'Croatia', 'Hrvatska', 'HRV', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (58, 'CU', 'Cuba', '', 'CUB', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (59, 'CW', 'Curacao', '', 'CUW', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (60, 'CY', 'Cyprus', '', 'CYP', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (61, 'CZ', 'Czech Republic', 'Česká republika', 'CZE', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (62, 'CD', 'Democratic Republic of Congo', '', 'COD', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (63, 'DK', 'Denmark', 'Danmark', 'DNK', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (64, 'DJ', 'Djibouti', '', 'DJI', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (65, 'DM', 'Dominica', '', 'DMA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (66, 'DO', 'Dominican Republic', 'República Dominicana', 'DOM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (67, 'TL', 'East Timor', '', 'TLS', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (68, 'EC', 'Ecuador', 'Ecuador', 'ECU', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (69, 'EG', 'Egypt', 'ﺮﺼﻣ', 'EGY', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (70, 'SV', 'El Salvador', 'El Salvador', 'SLV', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (71, 'GQ', 'Equatorial Guinea', '', 'GNQ', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (72, 'ER', 'Eritrea', '', 'ERI', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (73, 'EE', 'Estonia', 'Eesti', 'EST', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (74, 'ET', 'Ethiopia', '', 'ETH', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (75, 'FK', 'Falkland Islands (Malvinas)', '', 'FLK', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (76, 'FO', 'Faroe Islands', '', 'FRO', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (77, 'FJ', 'Fiji', '', 'FJI', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (78, 'FI', 'Finland', 'Suomi', 'FIN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (79, 'FR', 'France, Metropolitan', '', 'FRA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (80, 'GF', 'French Guiana', '', 'GUF', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (81, 'PF', 'French Polynesia', '', 'PYF', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (82, 'TF', 'French Southern Territories', '', 'ATF', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (83, 'MK', 'FYROM', '', 'MKD', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (84, 'GA', 'Gabon', '', 'GAB', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (85, 'GM', 'Gambia', '', 'GMB', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (86, 'GE', 'Georgia', '', 'GEO', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (87, 'DE', 'Germany', 'Deutschland', 'DEU', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (88, 'GH', 'Ghana', '', 'GHA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (89, 'GI', 'Gibraltar', '', 'GIB', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (90, 'GR', 'Greece', 'Ελλάδα', 'GRC', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (91, 'GL', 'Greenland', '', 'GRL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (92, 'GD', 'Grenada', '', 'GRD', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (93, 'GP', 'Guadeloupe', '', 'GLP', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (94, 'GU', 'Guam', '', 'GUM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (95, 'GT', 'Guatemala', 'Guatemala', 'GTM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (96, 'GG', 'Guernsey', '', 'GGY', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (97, 'GN', 'Guinea', '', 'GIN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (98, 'GW', 'Guinea-Bissau', '', 'GNB', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (99, 'GY', 'Guyana', '', 'GUY', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (100, 'HT', 'Haiti', '', 'HTI', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (101, 'HM', 'Heard and Mc Donald Islands', '', 'HMD', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (102, 'HN', 'Honduras', 'Honduras', 'HND', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (103, 'HK', 'Hong Kong', '香港', 'HKG', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (104, 'HU', 'Hungary', 'Magyarország', 'HUN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (105, 'IS', 'Iceland', 'Ísland', 'ISL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (106, 'IN', 'India', '', 'IND', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (107, 'ID', 'Indonesia', 'Indonesia', 'IDN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (108, 'IR', 'Iran (Islamic Republic of)', '', 'IRN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (109, 'IQ', 'Iraq', '', 'IRQ', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (110, 'IE', 'Ireland', 'Ireland', 'IRL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (111, 'IM', 'Isle of Man', '', 'IMN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (112, 'IL', 'Israel', 'לארשי', 'ISR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (113, 'IT', 'Italy', 'Italia', 'ITA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (114, 'JM', 'Jamaica', '', 'JAM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (115, 'JP', 'Japan', '日本', 'JPN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (116, 'JE', 'Jersey', '', 'JEY', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (117, 'JO', 'Jordan', 'ﻦﺪﺮﺄﻠﺍ', 'JOR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (118, 'KZ', 'Kazakhstan', '', 'KAZ', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (119, 'KE', 'Kenya', '', 'KEN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (120, 'KI', 'Kiribati', '', 'KIR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (121, 'XK', 'Kosovo, Republic of', '', 'UNK', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (122, 'KW', 'Kuwait', 'ﺖﻴﻮﻜﻠﺍ', 'KWT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (123, 'KG', 'Kyrgyzstan', '', 'KGZ', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (124, 'LA', 'Lao People\'s Democratic Republic', '', 'LAO', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (125, 'LV', 'Latvia', 'Latvija', 'LVA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (126, 'LB', 'Lebanon', 'ﻦﺎﻨﺐﻟ', 'LBN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (127, 'LS', 'Lesotho', '', 'LSO', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (128, 'LR', 'Liberia', '', 'LBR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (129, 'LY', 'Libyan Arab Jamahiriya', '', 'LBY', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (130, 'LI', 'Liechtenstein', 'Liechtenstein', 'LIE', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (131, 'LT', 'Lithuania', 'Lietuva', 'LTU', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (132, 'LU', 'Luxembourg', 'Luxembourg', 'LUX', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (133, 'MO', 'Macau', '', 'MAC', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (134, 'MG', 'Madagascar', '', 'MDG', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (135, 'MW', 'Malawi', '', 'MWI', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (136, 'MY', 'Malaysia', '', 'MYS', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (137, 'MV', 'Maldives', '', 'MDV', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (138, 'ML', 'Mali', '', 'MLI', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (139, 'MT', 'Malta', '', 'MLT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (140, 'MH', 'Marshall Islands', '', 'MHL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (141, 'MQ', 'Martinique', '', 'MTQ', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (142, 'MR', 'Mauritania', '', 'MRT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (143, 'MU', 'Mauritius', '', 'MUS', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (144, 'YT', 'Mayotte', '', 'MYT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (145, 'MX', 'Mexico', 'México', 'MEX', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (146, 'FM', 'Micronesia, Federated States of', '', 'FSM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (147, 'MD', 'Moldova, Republic of', '', 'MDA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (148, 'MC', 'Monaco', '', 'MCO', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (149, 'MN', 'Mongolia', '', 'MNG', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (150, 'ME', 'Montenegro', '', 'MNE', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (151, 'MS', 'Montserrat', '', 'MSR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (152, 'MA', 'Morocco', 'ﺔﻴﺐﺮﻐﻤﻠﺍ ﺔﻜﻠﻤﻤﻠﺍ', 'MAR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (153, 'MZ', 'Mozambique', '', 'MOZ', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (154, 'MM', 'Myanmar', '', 'MMR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (155, 'NA', 'Namibia', '', 'NAM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (156, 'NR', 'Nauru', '', 'NRU', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (157, 'NP', 'Nepal', '', 'NPL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (158, 'NL', 'Netherlands', 'Nederland', 'NLD', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (159, 'AN', 'Netherlands Antilles', '', 'ANT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (160, 'NC', 'New Caledonia', '', 'NCL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (161, 'NZ', 'New Zealand', 'New Zealand', 'NZL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (162, 'NI', 'Nicaragua', 'Nicarágua', 'NIC', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (163, 'NE', 'Niger', '', 'NER', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (164, 'NG', 'Nigeria', '', 'NGA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (165, 'NU', 'Niue', '', 'NIU', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (166, 'NF', 'Norfolk Island', '', 'NFK', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (167, 'KP', 'North Korea', '', 'PRK', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (168, 'MP', 'Northern Mariana Islands', '', 'MNP', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (169, 'NO', 'Norway', 'Norge', 'NOR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (170, 'OM', 'Oman', 'ﻦﺎﻤﻋ', 'OMN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (171, 'PK', 'Pakistan', '', 'PAK', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (172, 'PW', 'Palau', '', 'PLW', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (173, 'PS', 'Palestinian Territory, Occupied', '', 'PSE', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (174, 'PA', 'Panama', 'Panamá', 'PAN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (175, 'PG', 'Papua New Guinea', '', 'PNG', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (176, 'PY', 'Paraguay', 'Paraguay', 'PRY', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (177, 'PE', 'Peru', 'Perú', 'PER', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (178, 'PH', 'Philippines', '', 'PHL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (179, 'PN', 'Pitcairn', '', 'PCN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (180, 'PL', 'Poland', 'Polska', 'POL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (181, 'PT', 'Portugal', 'Portugal', 'PRT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (182, 'PR', 'Puerto Rico', '', 'PRI', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (183, 'QA', 'Qatar', 'ﺮﻄﻗ', 'QAT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (184, 'RE', 'Reunion', '', 'REU', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (185, 'RO', 'Romania', 'România', 'ROM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (186, 'RU', 'Russian Federation', 'Россия', 'RUS', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (187, 'RW', 'Rwanda', '', 'RWA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (188, 'KN', 'Saint Kitts and Nevis', '', 'KNA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (189, 'LC', 'Saint Lucia', '', 'LCA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (190, 'VC', 'Saint Vincent and the Grenadines', '', 'VCT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (191, 'WS', 'Samoa', '', 'WSM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (192, 'SM', 'San Marino', '', 'SMR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (193, 'ST', 'Sao Tome and Principe', '', 'STP', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (194, 'SA', 'Saudi Arabia', 'ﺔﻴﺪﻮﻌﺴﻠﺍ ﺔﻴﺐﺮﻌﻠﺍ ﺔﻜﻠﻤﻤﻠﺍ', 'SAU', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (195, 'SN', 'Senegal', '', 'SEN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (196, 'RS', 'Serbia', 'Srbija', 'SRB', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (197, 'SC', 'Seychelles', '', 'SYC', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (198, 'SL', 'Sierra Leone', '', 'SLE', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (199, 'SG', 'Singapore', '新加坡', 'SGP', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (200, 'SK', 'Slovak Republic', 'Slovenská republika', 'SVK', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (201, 'SI', 'Slovenia', 'Slovenija', 'SVN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (202, 'SB', 'Solomon Islands', '', 'SLB', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (203, 'SO', 'Somalia', '', 'SOM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (204, 'ZA', 'South Africa', 'South Africa', 'ZAF', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (205, 'GS', 'South Georgia &amp; South Sandwich Islands', '', 'SGS', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (206, 'KR', 'South Korea', '대한민국', 'KOR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (207, 'SS', 'South Sudan', '', 'SSD', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (208, 'ES', 'Spain', 'Espainia', 'ESP', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (209, 'LK', 'Sri Lanka', '', 'LKA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (210, 'BL', 'St. Barthelemy', '', 'BLM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (211, 'SH', 'St. Helena', '', 'SHN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (212, 'MF', 'St. Martin (French part)', '', 'MAF', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (213, 'PM', 'St. Pierre and Miquelon', '', 'SPM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (214, 'SD', 'Sudan', '', 'SDN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (215, 'SR', 'Suriname', '', 'SUR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (216, 'SJ', 'Svalbard and Jan Mayen Islands', '', 'SJM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (217, 'SZ', 'Swaziland', '', 'SWZ', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (218, 'SE', 'Sweden', 'Sverige', 'SWE', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (219, 'CH', 'Switzerland', 'Suisse', 'CHE', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (220, 'SY', 'Syrian Arab Republic', 'ﺎﻴﺮﻮﺳ', 'SYR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (221, 'TW', 'Taiwan', '台灣(中華民國)', 'TWN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (222, 'TJ', 'Tajikistan', '', 'TJK', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (223, 'TZ', 'Tanzania, United Republic of', '', 'TZA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (224, 'TH', 'Thailand', 'ไทย', 'THA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (225, 'TG', 'Togo', '', 'TGO', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (226, 'TK', 'Tokelau', '', 'TKL', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (227, 'TO', 'Tonga', '', 'TON', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (228, 'TT', 'Trinidad and Tobago', '', 'TTO', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (229, 'TA', 'Tristan da Cunha', '', 'SHN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (230, 'TN', 'Tunisia', 'ﺲﻨﻮﺗ', 'TUN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (231, 'TR', 'Turkey', 'Türkiye', 'TUR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (232, 'TM', 'Turkmenistan', '', 'TKM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (233, 'TC', 'Turks and Caicos Islands', '', 'TCA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (234, 'TV', 'Tuvalu', '', 'TUV', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (235, 'UG', 'Uganda', '', 'UGA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (236, 'UA', 'Ukraine', 'Україна', 'UKR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (237, 'AE', 'United Arab Emirates', 'ﺔﺪﺤﺘﻤﻠﺍ ﺔﻴﺐﺮﻌﻠﺍ ﺖﺎﺮﺎﻤﺈﻠﺍ', 'ARE', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (238, 'GB', 'United Kingdom', 'United Kingdom', 'GBR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (239, 'US', 'United States', 'United States', 'USA', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (240, 'UM', 'United States Minor Outlying Islands', '', 'UMI', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (241, 'UY', 'Uruguay', 'Uruguay', 'URY', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (242, 'UZ', 'Uzbekistan', '', 'UZB', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (243, 'VU', 'Vanuatu', '', 'VUT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (244, 'VA', 'Vatican City State (Holy See)', '', 'VAT', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (245, 'VE', 'Venezuela', 'Venezuela', 'VEN', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (246, 'VN', 'Viet Nam', 'Việt Nam', 'VNM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (247, 'VG', 'Virgin Islands (British)', '', 'VGB', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (248, 'VI', 'Virgin Islands (U.S.)', '', 'VIR', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (249, 'WF', 'Wallis and Futuna Islands', '', 'WLF', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (250, 'EH', 'Western Sahara', '', 'ESH', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (251, 'YE', 'Yemen', 'ﻦﻤﻴﻠﺍ', 'YEM', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (252, 'ZM', 'Zambia', '', 'ZMB', 1);
INSERT INTO `countries`(`id`, `code`, `name`, `native_name`, `iso_code_3`, `is_active`) VALUES (253, 'ZW', 'Zimbabwe', '', 'ZWE', 1);
